sudo: required
language: python

env:
  global:
    - DOCKER_IMAGE=alectolytic/rpmbuilder
    - COPR_REPOSITORY=throttled
    - OS_ARCH=x86_64
  matrix:
    - OS_TYPE=fedora OS_DIST=fedora OS_VERSION=32
    - OS_TYPE=fedora OS_DIST=fedora OS_VERSION=33

services:
  - docker

install: true

script:
  - docker run -v ${PWD}:/sources -v ${PWD}:/output:Z -e "SRPM_ONLY=1" ${DOCKER_IMAGE}:${OS_TYPE}-${OS_VERSION}

after_success:
  - pip install copr-cli simplejson
  - openssl aes-256-cbc -k $encryption_key -in .copr.enc -out .copr -d -iter 512
  - copr-cli --config .copr build -r ${OS_DIST}-${OS_VERSION}-${OS_ARCH} ${COPR_REPOSITORY} *.src.rpm
